image: docker-hub.squiz.net/au-client-implementation/docker-images/node:20

stages:
  - lint-and-test
  - build

lint-and-test:
  stage: lint-and-test
  tags:
    - docker
  script:
    - npm ci
    - npm run lint:css
    - npm run lint:js
    - npm run test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_BRANCH !~ /^deploy/


build:
  stage: build
  tags:
    - docker
  script:
    - npm ci
    - npm run lint:css
    - npm run lint:js
    - npm run test
    - npm run build
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_MESSAGE !~ /^\[WIP\]/ && $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == "main"
