// this file is auto-generated by the build-component-toc.js script
export const TOC = `<div class="col-12 col-lg-3 pe-lg-0 order-last order-lg-first mt-5 mt-lg-0">
            <div class="qld-side-navigation">
            
                <h2 class="nav-title">
                    <a class="nav-link" href="#optionallink">Component Examples</a>
                </h2>

                 <!-- Level One -->
                <ul class="nav" aria-label="section navigation">

                    <li class="nav-item">
                        <a class="nav-link" href="/accordion">Accordion Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/accordion-dynamic">Dynamic Accordion Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blockquote">Blockquote Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/callout">Callout Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/card">Card Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/card-curated-3col">Card Curated 3 Columns</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/card-dynamic">Dynamic Card Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/card-multi-action">Card Multi-action</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/card-related-3col">Card Related 3 Columns</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/events-list">Events List Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/inpage-alert">Inpage Alert Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/links-list">Links List Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/pagination">Pagination Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/table">Table Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/tag-dynamic">Dynamic Tag Component</a>
                      </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/video">Video Component</a>
                      </li>
            
                </ul>
            </div>
        </div>`;

export const tocNames = [
	'accordion',
	'accordion-dynamic',
	'blockquote',
	'callout',
	'card',
	'card-curated-3col',
	'card-dynamic',
	'card-multi-action',
	'card-related-3col',
	'events-list',
	'inpage-alert',
	'links-list',
	'pagination',
	'table',
	'tag-dynamic',
	'video'
];